ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER CAMILY IDENTIFIED BY "1111";
GRANT DBA TO CAMILY;
/*
    테이블 종류
    MEMBER          -- 회원정보
    CAMPING         -- 캠핑장
    GOODS           -- 캠핑용품
    BOARDS          -- 게시판
    REPLYS          -- 리플
    CAMPINGREVIEW   -- 캠핑 리뷰
    GOODSREVIEW     -- 상품 리뷰
    RESERVATION     -- 캠핑장 예매 테이블
    GOODSORDER      -- 주문 정보 테이블
*/
select * from members;
select * from goodsreview;
select * from goodsorder;
select * from reservation;
select * from camping ORDER BY CACODE DESC;

-- 회원 테이블
CREATE TABLE MEMBERS(
    MID	        NVARCHAR2(10),      -- 아이디 (PK)
	MPW         NVARCHAR2(10),      -- 비밀번호 (NOT NULL)
	MNAME       NVARCHAR2(5),       -- 이름 (NOT NULL)
	MTEL        NVARCHAR2(13),      -- 전화번호 (NOT NULL)
	MEMAIL      NVARCHAR2(50),      -- 이메일 (NOT NULL)
	MBIRTH      DATE,               -- 생년월일
    MADDR       NVARCHAR2(100),     -- 주소
	MSTATE      NVARCHAR2(4),       -- 회원상태 GN(일반), KA(카카오), AD(관리자) // 00: 이용정지, 01: 사용가능
	MRANK       NVARCHAR2(4),	    -- 회원등급 "신규"
    MKAKAOKEY   NUMBER(15),         -- 카카오 로그인 키
    MNAVERKEY   NVARCHAR2(50)       -- 네이버 로그인 키                     
);	

SELECT * FROM MEMBERS;

ALTER TABLE MEMBERS
ADD CONSTRAINT PK_MID PRIMARY KEY(MID);

ALTER TABLE MEMBERS MODIFY MPW NOT NULL;
ALTER TABLE MEMBERS MODIFY MNAME NOT NULL;
ALTER TABLE MEMBERS MODIFY MTEL NOT NULL;
ALTER TABLE MEMBERS MODIFY MEMAIL NOT NULL;

-- 캠핑장 테이블
CREATE TABLE CAMPING(
    CACODE          NVARCHAR2(5),       -- 캠핑장 코드 (PK)
    CANAME          NVARCHAR2(20),      -- 캠핑장 이름 (NOT NULL)
    CALATITUDE      NVARCHAR2(15),      -- 캠핑장 위도 (NOT NULL)
    CALONGITUDE     NVARCHAR2(15),      -- 캠핑장 경도 (NOT NULL)
    CACONTENTS      NVARCHAR2(500),     -- 캠핑장 소개
    CAPRICE         NVARCHAR2(10),      -- 캠핑장 가격 (NOT NULL)
    CAINFO          NVARCHAR2(100),     -- 캠핑장 시설정보
    CAIMAGE         NVARCHAR2(100)      -- 캠핑장 이미지
);

ALTER TABLE CAMPING
ADD CONSTRAINT PK_CACODE PRIMARY KEY(CACODE);
ALTER TABLE CAMPING MODIFY CANAME NOT NULL;
ALTER TABLE CAMPING MODIFY CALATITUDE NOT NULL;
ALTER TABLE CAMPING MODIFY CALONGITUDE NOT NULL;
ALTER TABLE CAMPING MODIFY CAPRICE NOT NULL;


-- 캠핑용품 테이블
CREATE TABLE GOODS(
    GCODE      NVARCHAR2(5),       -- 상품 코드 (PK)
    GNAME      NVARCHAR2(20),      -- 상품 이름 (NOT NULL)
    GPRICE     NVARCHAR2(10),      -- 상품 가격 (NOT NULL)
    GCATEGORY  NVARCHAR2(10)       -- 상품 카테고리
);
select * from campingreview;
SELECT * FROM GOODSREVIEW;
select * from members;

    
ALTER TABLE GOODS
ADD CONSTRAINT PK_GCODE PRIMARY KEY(GCODE);
ALTER TABLE GOODS MODIFY GNAME NOT NULL;
ALTER TABLE GOODS MODIFY GPRICE NOT NULL;

SELECT * FROM GOODS;

-- 게시판 테이블
CREATE TABLE BOARDS(
    BOCODE      NUMBER(5),          -- 게시판 코드 (PK)
    BOMID       NVARCHAR2(10),      -- 게시판 작성자 (FK)
    BOTYPE      NUMBER(1),          -- 게시판 종류 (0: 공지게시판, 1: 자유게시판, 2: 질문게시판, 3: 건의게시판)
    BOTITLE     NVARCHAR2(50),      -- 게시판 이름 (NOT NULL)
    BOCONTENTS  NVARCHAR2(1000),    -- 게시판 글내용
    BODATE      DATE,               -- 게시판 작성일
    BOSTATE     NUMBER(1)           -- 게시판 상태   
);
select * from boards;
select * from faq;


ALTER TABLE BOARDS
ADD CONSTRAINT PK_BOCODE PRIMARY KEY(BOCODE);
ALTER TABLE BOARDS
ADD CONSTRAINT FK_BOMID FOREIGN KEY(BOMID) REFERENCES MEMBERS(MID);
ALTER TABLE BOARDS MODIFY BOTITLE NOT NULL;
    
-- 리플 테이블
CREATE TABLE REPLYS(
    RPCODE NUMBER(5),           -- 덧글 코드 (PK)
    RPMID NVARCHAR2(10),        -- 덧글 작성자 (KF)
    RPBOCODE NUMBER(5),         -- 덧글 작성한 글 코드 (FK)
    RPDATE DATE,
    RPCONTENTS NVARCHAR2(200),   -- 덧글 내용 (NOT NULL)
    RPSTATE NUMBER(1)
);

insert into REPLYS(RPCODE, RPMID, RPBOCODE, RPDATE, RPCONTENTS)
                values(2, 'kds1234', 2, sysdate, '안녕하세요2!');
ALTER TABLE REPLYS
ADD CONSTRAINT PK_RPCODE PRIMARY KEY(RPCODE);
ALTER TABLE REPLYS
ADD CONSTRAINT FK_RPMID FOREIGN KEY(RPMID) REFERENCES MEMBERS(MID);
ALTER TABLE REPLYS
ADD CONSTRAINT FK_RPBOCODE FOREIGN KEY(RPBOCODE) REFERENCES BOARDS(BOCODE);
ALTER TABLE REPLYS MODIFY RPCONTENTS NOT NULL;

SELECT * FROM REPLYS;
DROP TABLE REPLYS;
select * from camping;
-- 캠핑 리뷰 테이블
CREATE TABLE CAMPINGREVIEW(
    CGRVCODE        NUMBER(5),       -- 캠핑장 리뷰 코드 (PK)
    CGRVRECODE      NVARCHAR2(5),    --  캠핑장 예약 코드 
    CGRVMID         NVARCHAR2(10),      -- 캠핑장 리뷰 작성자 (FK)
    CGRVCACODE      NVARCHAR2(7),       -- 리뷰 쓸 캠핑장 코드 (FK)
    CGRVTITLE       NVARCHAR2(50),      -- 캠핑장 리뷰 제목 (NOT NULL)
    CGRVCONTENTS    NVARCHAR2(200),     -- 캠핑장 리뷰 내용 (NOT NULL)
    CGRVDATE        DATE,               -- 캠핑장 리뷰 날짜
    CGRVLIKE        NUMBER(1),          -- 캠핑장 좋아요(0: 없음, 1: 좋아요)
    CGRVIMAGE       NVARCHAR2(100),
    CGRVSTATE       NUMBER(1),
    CGRVHITS        NUMBER(10)
);
SELECT DISTINCT CA.CAIMAGE, RE.RECRNAME, CG.CGRVRECODE, CGRVCODE, CGRVMID, CGRVCACODE, CGRVTITLE, CGRVCONTENTS, TO_CHAR(CGRVDATE, 'YYYY-MM-DD HH24:MI')AS CGRVDATE, CGRVLIKE, CGRVSTATE
FROM CAMPINGREVIEW CG, RESERVATION RE, CAMPING CA
WHERE CG.CGRVCACODE = RE.RECACODE
AND CA.CACODE = RE.RECACODE
AND CG.CGRVRECODE = RE.RECODE
AND CGRVCODE = 4
ORDER BY CGRVCODE;
select * from campingreview;

SELECT * FROM CAMPINGREVIEW;
SELECT * FROM RESERVATION;
select * from goods;
SELECT * FROM RESERVATION;
select * from campingreview;
drop table campingreview;

select * from goodsreview;

ALTER TABLE CAMPINGREVIEW
ADD CONSTRAINT PK_CGRVCODE PRIMARY KEY(CGRVCODE);
ALTER TABLE CAMPINGREVIEW
ADD CONSTRAINT FK_CGRVMID FOREIGN KEY(CGRVMID) REFERENCES MEMBERS(MID);
ALTER TABLE CAMPINGREVIEW
ADD CONSTRAINT FK_CGRVCACODE FOREIGN KEY(CGRVCACODE) REFERENCES CAMPING(CACODE);
ALTER TABLE CAMPINGREVIEW MODIFY CGRVCONTENTS NOT NULL;
ALTER TABLE CAMPINGREVIEW MODIFY CGRVTITLE NOT NULL;


-- 상품 리뷰 테이블
CREATE TABLE GOODSREVIEW(
    GORVCODE        NUMBER(5),          -- 상품 리뷰 코드
    GORVMID         NVARCHAR2(10),      -- 상품 리뷰 작성자
    GORVGCODE       NVARCHAR2(5),       -- 리뷰 쓸 상품 코드
    GORVTITLE       NVARCHAR2(50),      -- 리뷰 제목
    GORVCONTENTS    NVARCHAR2(200),     -- 상품 리뷰 내용
    GORVGOCODE      NVARCHAR2(5),       -- 상품 주문번호
    GOIMAGE         NVARCHAR2(100),     -- 상품 이미지
    GORVDATE        DATE,               -- 상품 리뷰 날짜
    GORVLIKE        NUMBER(1),          -- 상품 추천(1),비추천(0)
    GORVHITS        NUMBER(10)
);
insert into GOODSREVIEW(GORVCODE, GORVMID, GORVGCODE, GORVTITLE, GORVCONTENTS, GORVDATE, GORVLIKE)
                values(1, 'jhy1234', 'GD018', '포레스트체어 사용후기!', '1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기1박2일 이용후기', 
                SYSDATE, 1);
                
ALTER TABLE GOODSREVIEW
ADD CONSTRAINT PK_GORVCODE PRIMARY KEY(GORVCODE);
ALTER TABLE GOODSREVIEW
ADD CONSTRAINT FK_GORVMID FOREIGN KEY(GORVMID) REFERENCES MEMBERS(MID);
ALTER TABLE GOODSREVIEW
ADD CONSTRAINT FK_GORVGCODE FOREIGN KEY(GORVGCODE) REFERENCES GOODS(GCODE);
ALTER TABLE GOODSREVIEW
ADD CONSTRAINT FK_GORVGOCODE FOREIGN KEY(GORVGOCODE) REFERENCES GOODSORDER(GOCODE);
ALTER TABLE GOODSREVIEW MODIFY GORVCONTENTS NOT NULL;
ALTER TABLE GOODSREVIEW MODIFY GORVTITLE NOT NULL;
SELECT * FROM GOODSREVIEW;
DROP TABLE GOODSREVIEW;
commit;
-- 캠핑장 예매 테이블
CREATE TABLE RESERVATION(
    RECODE      NUMBER(5),   -- 예매 코드 (PK)
    RECACODE    NVARCHAR2(5),   -- 예매 캠핑장 코드 (FK)
    REMID       NVARCHAR2(10),  -- 예매자 아이디 (FK)
    RESTARTDAY  DATE,           -- 예매 시작일
    REENDDAY    DATE,           -- 예매 종료일
    REPEOPLE    NUMBER,         -- 예매 인원
    REIMAGE     NVARCHAR2(50)   -- 이미지
);
select * from campingreservation;
desc reservation;
select * from reservation;
ALTER TABLE RESERVATION
ADD CONSTRAINT PK_RECODE PRIMARY KEY(RECODE);
ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RECACODE FOREIGN KEY(RECACODE) REFERENCES CAMPING(CACODE);
ALTER TABLE RESERVATION
ADD CONSTRAINT FK_REMID FOREIGN KEY(REMID) REFERENCES MEMBERS(MID);



-- 주문 정보 테이블
CREATE TABLE GOODSORDER(
    GOCODE      NVARCHAR2(5),   -- 주문 코드 (PK)
    GOMID       NVARCHAR2(10),  -- 주문자 아이디 (FK)
    GOMADDR     NVARCHAR2(100), -- 주문 주소
    GOGCODE     NVARCHAR2(5),   -- 주문 상품 코드 (FK)
    GOAMOUNT    NUMBER,         -- 주문 수량
    GOPRICE     NVARCHAR2(10)   -- 주문 상품 개당 가격 (FK) -- GOODS과 같은?
);
ALTER TABLE GOODSORDER
ADD CONSTRAINT PK_GOCODE PRIMARY KEY(GOCODE);
ALTER TABLE GOODSORDER
ADD CONSTRAINT FK_GOMID FOREIGN KEY(GOMID) REFERENCES MEMBERS(MID);
ALTER TABLE GOODSORDER
ADD CONSTRAINT FK_GOGCODE FOREIGN KEY(GOGCODE) REFERENCES GOODS(GCODE);
select * from faq;

-- 회원가입 쿼리문
INSERT INTO MEMBERS(MID,MPW,MNAME,MTEL,MEMAIL,MBIRTH,MADDR,MSTATE,MRANK,MKAKAOKEY)
VALUES();

-- 로그인 쿼리문
SELECT MID
FROM MEMBERS
WHERE MID AND MPW;

-- 로그인 중복 확인
SELECT MID
FROM MEMBERS
WHERE MID;

-- 내정보 
SELECT*
FROM MEMBERS
WHERE MID;

select * from members;

delete members
where mid like '%a%';

select *
from members
where mid like '%a%';
commit;






